debug: true
algorithm:
  type: cpu
  width: 640
  height: 640
  artifact-name: model/classes.txt
  model-path: model/retinaface.zip
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8181
